service: cannabis-news-bot

frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: python3.9
  stage: ${opt:stage, 'dev'}
  region: us-east-1

  environment:
    OPENAI_API_KEY: ${ssm:OPENAI_API_KEY}
    TWITTER_CONSUMER_KEY: ${ssm:TWITTER_CONSUMER_KEY}
    TWITTER_CONSUMER_SECRET: ${ssm:TWITTER_CONSUMER_SECRET}
    TWITTER_ACCESS_TOKEN: ${ssm:TWITTER_ACCESS_TOKEN}
    TWITTER_ACCESS_TOKEN_SECRET: ${ssm:TWITTER_ACCESS_TOKEN_SECRET}
    TWITTER_BEARER_TOKEN: ${ssm:TWITTER_BEARER_TOKEN}
    CANNABISNEWSAPIKEY: ${ssm:CANNABISNEWSAPIKEY}
    CANNABIS_NEWS_ENDPOINT: ${ssm:CANNABIS_NEWS_ENDPOINT}
    CANNABIS_NEWS_UPDATE_ENDPOINT: ${ssm:CANNABIS_NEWS_UPDATE_ENDPOINT}

functions:
  fetchNewsArticles:
    handler: twitter_news_bot.data_fetcher.lambda_handler
    timeout: 30
    events:
      - http:
          path: fetchNews
          method: get

  generateTweet:
    handler: twitter_news_bot.openai_api.lambda_handler
    timeout: 30
    events:
      - http:
          path: generateTweet
          method: post
    
  postTweet:
    handler: twitter_news_bot.twitter_api.lambda_handler
    timeout: 30
    events:
      - http:
        path: postTweet
        method: post


package:
  exclude:
    - venv/**
    - tests/**
    - logs/**

plugins:
  - serverless-python-requirements
  - serverless-dotenv-plugin
  - serverless-offline
  
custom:
  pythonRequirements:
    dockerizePip: non-linux
